repository: yuki-fang/projects-portfolio

# Site settings
title: Yu-Qi (Yuki) Fang
email: yu-qifang2025@u.northwestern.edu
description: >- 
  Aspiring Marketing Analyst looking to bridge the gap between data and creativity to drive smarter brand decisions. 
github_username: yukifang
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:title/
timezone: "America/Chicago"

include:
  - _pages

# Exclude from processing
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (only keep necessary ones)
plugins:
  - jekyll-sitemap
  - jekyll-feed

author:
  name: "Yu-Qi (Yuki) Fang"
  avatar: "/assets/images/yuki.jpg"
  bio: "M.S. in Integrated Marketing Communications @ Northwestern | Data-Driven Marketer"
  links:
    - label: "Resume"
      icon: "fas fa-fw fa-file"
      url: "/assets/YukiFang_Resume.pdf"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "yu-qifang2025@u.northwestern.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yuki-fang/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yuki-fang"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "yu-qifang2025@u.northwestern.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/yuki-fang/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yuki-fang"

# Defaults for pages
defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Show your About page as homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Set About as homepage
# Replace 'about' if your page filename is different
# For example, if your about page is `_pages/about.md`
# And its permalink is `/about/`, you want to override the root `/`

collections:
  pages:
    output: true

# Set the homepage manually
# Point to the about page path
# Assuming your about page is at _pages/about.md with permalink /about/
# You’ll make a copy and link it to the root

# Option 1: Rename and repoint permalink
# _pages/index.md
title: "About"
layout: single
author_profile: true
permalink: /

# Include your about content here or pull from another file
